services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\ApiBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,PostWriteEvent,PhpGuildApiBundle.php}'

  PhpGuild\ApiBundle\EventSubscriber\AuthenticationSuccessListener:
    tags:
      - name: kernel.event_listener
        event: lexik_jwt_authentication.on_authentication_success
        method: onAuthenticationSuccessResponse
